In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size

voc_size = 10000    

In [5]:
### One Hot representation for every word

one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[2294, 3226, 5559, 5998],
 [2294, 3226, 5559, 1230],
 [2294, 833, 5559, 8806],
 [9856, 2721, 5286, 476, 1537],
 [9856, 2721, 5286, 476, 2133],
 [4712, 2294, 2434, 5559, 5649],
 [6241, 3374, 5103, 476]]

In [6]:
## word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2294 3226 5559 5998]
 [   0    0    0    0 2294 3226 5559 1230]
 [   0    0    0    0 2294  833 5559 8806]
 [   0    0    0 9856 2721 5286  476 1537]
 [   0    0    0 9856 2721 5286  476 2133]
 [   0    0    0 4712 2294 2434 5559 5649]
 [   0    0    0    0 6241 3374 5103  476]]


In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
## feature representation

dim = 10

In [11]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 29ms/step


array([[-9.72374529e-03,  6.06876612e-03, -1.74052827e-02,
         4.14402522e-02,  2.78188325e-02,  2.25778930e-02,
        -4.37812209e-02, -4.67801355e-02, -2.74080876e-02,
         4.07418050e-02],
       [-9.72374529e-03,  6.06876612e-03, -1.74052827e-02,
         4.14402522e-02,  2.78188325e-02,  2.25778930e-02,
        -4.37812209e-02, -4.67801355e-02, -2.74080876e-02,
         4.07418050e-02],
       [-9.72374529e-03,  6.06876612e-03, -1.74052827e-02,
         4.14402522e-02,  2.78188325e-02,  2.25778930e-02,
        -4.37812209e-02, -4.67801355e-02, -2.74080876e-02,
         4.07418050e-02],
       [-9.72374529e-03,  6.06876612e-03, -1.74052827e-02,
         4.14402522e-02,  2.78188325e-02,  2.25778930e-02,
        -4.37812209e-02, -4.67801355e-02, -2.74080876e-02,
         4.07418050e-02],
       [-4.95773219e-02, -3.29777375e-02, -3.12792659e-02,
        -3.99432294e-02, -1.26425512e-02, -1.76817067e-02,
         4.97259013e-02, -4.05807011e-02,  4.28245179e-02,
         6.